#!/usr/bin/python
# -*- coding: cp1252 -*-
#    Copyright 2013, Chaz Littlejohn 
#        ________  ____  _   __   ________  ______________
#       /  _/ __ \/ __ \/ | / /  / ____/ / / / ____/ ____/
#       / // /_/ / / / /  |/ /  / /   / /_/ / __/ / /_    
#     _/ // _, _/ /_/ / /|  /  / /___/ __  / /___/ __/    
#    /___/_/ |_|\____/_/ |_/   \____/_/ /_/_____/_/       
#                                                         
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#    
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#    GNU General Public License for more details.
#    
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

########################################################################

listing = [
("ishinabe vs maruyama takeshi (salmon)","01","01"),
("michiba vs kobayakawa yousei (foie gras)","01","02"),
("chen vs indoragori paulo (blow fish)","01","03"),
("chen vs kudo toshiyuki (tofu)","01","04"),
("michiba vs syu tomiteru (lobster)","01","05"),
("chen vs tei kazuhiko (octopus)","01","06"),
("ishinabe vs muto masato (radish)","01","07"),
("michiba vs syu tomitoku (crab)","01","08"),
("ishinabe vs oyama eizo (banana)","01","09"),
("ishinabe vs jacques borie (chicken)","01","10"),
("michiba vs shu tomitoku (pork)","02","01"),
("chen vs wan weiping (squid)","02","02"),
("michiba vs hoshino jun (egg)","02","03"),
("michiba vs tanabe toshio (sea bream)","02","04"),
("chen vs taniguchi kouichi (shrimp)","02","05"),
("michiba vs masaki kazuyoshi (anago eel )","02","06"),
("chen vs kandagawa toshiro (flounder)","02","07"),
("sakai vs guy shokr (oyster)","02","08"),
("chen vs kondo shinji (wheat)","02","09"),
("sakai vs kitami hiroyuki (tomato)","02","10"),
("chen vs kagata kyoko (scallop)","02","11"),
("michiba vs otakura hideaki (cheese)","02","12"),
("michiba vs goto koichiro (rice)","02","13"),
("chen vs munetaka takahashi (bamboo shoots)","02","14"),
("sakai vs mario nakagawa (lamb)","02","15"),
("michiba vs yukio hattori (truffle)","02","16"),
("chen vs hiromi yamada (cabbage)","02","17"),
("sakai vs hiromi funatsu (bonito)","02","18"),
("sakai vs masatoshi kimura (duck)","02","19"),
("chen vs kiyoshi takahashi (carrot)","02","20"),
("michiba vs kuniyuki ishikawa (natto)","02","21"),
("michiba vs katsumi hanato (sweetfish)","02","22"),
("sakai vs yuji wakiya (sea urchin)","02","23"),
("chen vs masahiko miyamoto (milk)","02","24"),
("chen vs koichi tabata (eggplant)","02","25"),
("michiba vs takashi mera (tuna)","02","26"),
("sakai vs tadaaki shimizu (homard (lobster))","02","27"),
("michiba and chen vs joël bruant and masafumi furutaka (sea bass)","02","28"),
("sakai vs mitsuru saito (beef)","02","29"),
("michiba vs yasuhiko yoshida (eel)","02","30"),
("sakai vs hirohisa koyama (pike eel)","02","31"),
("chen vs katsuyo kobayashi (potato)","02","32"),
("michiba vs keiji nakazawa (corn)","02","33"),
("chen vs hideki ohsako (mushroom)","02","34"),
("michiba vs artur j. rütter (bell pepper)","02","35"),
("michiba vs tsutomu hiroi (saury)","02","36"),
("sakai vs sotetsu fuji (yam potato)","02","37"),
("chen vs takashi saito (prawn)","02","38"),
("sakai vs masamitsu takahashi (matsutake mushrooms)","02","39"),
("michiba vs xu peirong (shark fin)","02","40"),
("sakai vs sekihata katsuyuki (bread)","02","41"),
("chen vs koji kobayashi (pumpkin)","02","42"),
("michiba vs yasuo kawada (anglerfish)","02","43"),
("chin vs sugita tadashi (shanghai crab)","02","44"),
("michiba vs tatsuo umemiya (horse mackerel)","02","45"),
("sakai vs seiya kawasaki (quail)","02","46"),
("chen vs toshikatsu nakagawa (noodle)","02","47"),
("michiba vs hiroshi furusho (turkey)","02","48"),
("sakai vs masayo waki (strawberry)","02","49"),
("mr. iron chef 1994: preliminaries","02","50"),
("mr. iron chef 1994: final (yellowtail)","03","01"),
("chen vs toshiyuki nakagawa (mochi)","03","02"),
("sakai vs koji yamada (turnip)","03","03"),
("chen vs hisao oidate (chinese cabbage)","03","04"),
("sakai vs fuyuko kondo (apple & chocolate)","03","05"),
("chen vs yoshie urabe (soybean)","03","06"),
("michiba vs masao suzuki (matsuba crab)","03","07"),
("chen vs kunihiko hashimoto (taro)","03","08"),
("sakai vs toshihiro komine (asparagus)","03","09"),
("michiba vs wang zhijian (egg)","03","10"),
("chen vs tetsutoshi shimazu (squid)","03","11"),
("sakai vs shigeo yuasa (cod)","03","12"),
("hong kong special","03","13"),
("chen vs chiyo cho (tofu)","03","14"),
("ishinabe vs sawaguchi tomoyuki (flounder)","03","15"),
("sakai vs kunio santo (clam)","03","16"),
("michiba vs keisuke tamano (tilefish)","03","17"),
("chen vs lee myong suk (liver)","03","18"),
("sakai vs isao yanagidate (caviar)","03","19"),
("chen vs elio orsara (kajiki tuna)","03","20"),
("michiba vs etsuo joh (broccoli)","03","21"),
("sakai vs katsuo ohmiya (onion)","03","22"),
("sakai vs kazutaka okabe (lamb)","03","23"),
("michiba vs zeng mingxing (blue crab)","03","24"),
("chen vs yukihiro noda (sardine)","03","25"),
("ishinabe vs yanagidate isao (avocado)","03","26"),
("sakai vs takayoshi kawai (sole)","03","27"),
("sakai vs haruyoshi omino (sweetfish)","03","28"),
("chen vs li jinlun (swallow's nest)","03","29"),
("sakai vs shinichi nagamatsu (eggplant)","03","30"),
("chen vs hisama hirano (sea urchin)","03","31"),
("michiba vs kenji kaji (umeboshi)","03","32"),
("michiba and sakai vs the cuomo brothers (tomato)","03","33"),
("chen vs yoshiko takemasa (short-necked clam)","03","34"),
("sakai vs joël bruant (salmon)","03","35"),
("michiba vs minoru noda (matsutake mushroom)","03","36"),
("sakai vs philippe aubron (crayfish)","03","37"),
("chen vs tsuguo fujiwara (sea cucumber)","03","38"),
("1995 iron chef world cup","03","39"),
("sakai vs sadaharu nakajima (rice)","03","40"),
("michiba vs lin kunbi (potato)","03","41"),
("michiba vs lin kunbi (sweet potato)","03","42"),
("chen vs masahiko hagiwara (scampi)","03","43"),
("chen vs kiyotaka ikegawa (horsehair crab)","03","44"),
("sakai vs toshiro kandagawa (lotus root)","03","45"),
("sakai vs bruno ménard (escargot)","03","46"),
("chen vs sozo miyamoto (carp)","03","47"),
("sakai vs tadamichi ohta (octopus)","03","48"),
("sakai vs philippe groult (oyster)","03","49"),
("mr iron chef 1995: chen vs sakai (chicken)","03","50"),
("mr iron chef 1995 :chen vs michiba (beef)","04","01"),
("the legend of michiba","04","02"),
("chen vs gao jinyi (dried abalone)","04","03"),
("sakai vs hidetoshi ushimaru (curry powder)","04","04"),
("chen vs hiroshi yamanobe (scorpionfish)","04","05"),
("chen vs watanabe yoji (snapping turtle)","04","06"),
("sakai vs tadashi yanagi (pear & chocolate)","04","07"),
("sakai vs jinichi tateyama (leek)","04","08"),
("chen vs takaya nakazawa (shiitake mushroom)","04","09"),
("nakamura vs kiyoshi suzuki (foie gras)","04","10"),
("chen vs tatsujiro yoshida (cod)","04","11"),
("sakai vs senji osada (scallop)","04","12"),
("nakamura vs lin kunbi (bell pepper)","04","13"),
("chen vs katsuaki mori (spinach)","04","14"),
("france special part i: nakamura vs bernard leprince (salmon)","04","15"),
("france special part ii: sakai vs pierre gagnaire (homard lobster)","04","16"),
("nakamura vs toyoaki suganuma (egg)","04","17"),
("chen vs he yewen (lettuce)","04","18"),
("nakamura vs katsuko nanao (cod roe)","04","19"),
("chen vs shunji morikawa (pineapple)","04","20"),
("sakai vs takao tamotsu (abalone)","04","21"),
("nakamura vs kenji motai (udon)","04","22"),
("chen vs goto ichio (cuttlefish)","04","23"),
("sakai vs sonobe yoshinobu (salmon roe)","04","24"),
("nakamura vs son kangi (bonito)","04","25"),
("sakai vs philippe batton (bacon)","04","26"),
("nakamura vs tozawa hideo (clam)","04","27"),
("chen vs nomura takayuk (ayu)","04","28"),
("nakamura vs yamamoto hideki (conger)","04","29"),
("sakai vs uki yoshimasa (tuna)","04","30"),
("nakamura vs toriumi masaru (oyster)","04","31"),
("chen vs yamamoto takeshi (pork)","04","32"),
("nakamura vs thierry houngues (caviar)","04","33"),
("chen vs tsugawa toshizo (sea eel)","04","34"),
("sakai vs sugawara ken'ji (corn)","04","35"),
("chen vs shinsuke shimada (fleshy prawn)","04","36"),
("nakamura vs uetake toshimasa (peach)","04","37"),
("sakai vs so choumei (softcrab)","04","38"),
("nakamura vs endo tokuo (mackerel pike)","04","39"),
("chen vs kashiwabara takeo (wax gourd)","04","40"),
("beijing special: chen vs son-so (chicken)","04","41"),
("chen over time (shark fin)","04","41"),
("nakamura vs fujita shin (soba)","04","42"),
("nakamura vs ogusu ryuichi (chestnut)","04","43"),
("chen vs daniela ozik (mushroom)","04","44"),
("sakai vs yamaoka hiroshi (chinese cabbage)","04","45"),
("sakai vs wein nishi (apple)","04","46"),
("nakamura vs kuroki kenjiro (angler)","04","47"),
("nakamura vs miyashiro kiyoshi (cow's tongue)","04","48"),
("chen vs ishizaki yukio (garlic)","04","49"),
("sakai vs suzuki yoshio (orange)","04","50"),
("nakamura vs belnare lebrance (gull)","04","51"),
("nakamura vs michiba (pork, sweet potato, and octopus)","04","52"),
("sakai vs kasahara hiroshi (rice cake)","05","01"),
("chen vs michifude hiroshi (dried scallop)","05","02"),
("sakai vs rory kennedy (rabbit)","05","03"),
("sakai vs rory kennedy (pigeon) overtime","05","04"),
("nakamura vs morieda hiroyoshi (crab)","05","05"),
("chen vs kou houkou (rice)","05","06"),
("sakai vs shimada tetsuya (truffle)","05","07"),
("nakamura vs yamazaki tateo (nattou)","05","08"),
("sakai vs jyo etsuo (wine)","05","09"),
("chen vs wakiya yuji (papaya)","05","10"),
("nakamura vs mera takashi (seaweed)","05","11"),
("sakai vs kitami hiroyuki (honey)","05","12"),
("nakamura vs you koukan (hanami festival)","05","13"),
("sakai vs okumura shinzou (bamboo shoot)","05","14"),
("chen vs ootsuki chihiro (tomato)","05","15"),
("sakai vs sasaki kiyoyasu (perch)","05","16"),
("nakamura vs azumaya norio (pork)","05","17"),
("nakamura vs jillian harst (ostrich)","05","18"),
("chen vs takagi masao (duck's egg)","05","19"),
("sakai vs germano orsara (ham)","05","20"),
("nakamura vs sakane hisahito (sea eel)","05","21"),
("kobe vs hagiwara masahiko (pasta)","05","22"),
("sakai vs sato norio (amberjack - kampachi)","05","23"),
("chen vs syu kenchu (akahata - grouper)","05","24"),
("nakamura vs kashima masami (prawn)","05","25"),
("sakai vs ishikawa toshiyuki (sea urchin)","05","26"),
("chen vs matsuno yoshikazu (mantis shrimp - shako)","05","27"),
("kobe vs stephan tabacchi (cabbage)","05","28"),
("sakai vs toyoshima seiji (milk)","05","29"),
("nakamura chin vs sakai kobe (watermelon)","05","30"),
("chen vs souseiko kawaguchi (eggplant)","05","31"),
("sakai vs androsoni pietro (melon)","05","32"),
("nakamura vs kojima koten (potato)","05","33"),
("nakamura vs kojima koten (flatfish) overtime","05","34"),
("sakai vs nakajima toshiyuki (cow's cheek)","05","35"),
("chen vs igarashi miyuki (cucumber)","05","36"),
("kobe vs imai fujio (matsutake)","05","37"),
("1997 world cup","05","38"),
("chen vs nagasaka matsuo (spareribs)","05","39"),
("sakai vs goto masashi (prawn)","05","40"),
("kobe vs seki yuji (chestnut)","05","41"),
("nakamura vs azuma keiji (lamb)","05","42"),
("chen vs matsushima toru (crab)","05","43"),
("kobe vs takahashi kazunari (milt)","05","44"),
("kobe vs takahashi kazunari (shrimp) over time","05","45"),
("nakamura vs moris guilett (scallop)","05","46"),
("kobe vs takagi yasumasa (strawberry)","05","47"),
("nakamura vs kandagawa toshiro (longtooth grouper)","05","48"),
("chen vs inoue akihiko (aramaki salmon)","06","01"),
("kobe vs fukazu yasuhiro (deer)","06","02"),
("sakai vs matsumoto yoshimasa (pine needle crab)","06","03"),
("chen vs tou choki (black tiger)","06","04"),
("sakai vs sato fumiaki (radish)","06","05"),
("nakamura retirement special","06","06"),
("nakamura's retirement special (tuna) part ii","06","07"),
("morimoto vs hirayama yukio (red snapper)","06","08"),
("sakai vs kondo motohito (girls' festival)","06","09"),
("kobe vs mario frittoli (broccoli)","06","10"),
("morimoto vs kimura masayoshi (rice)","06","11"),
("sakai vs tomoji ichikawa (guinea fowl)","06","12"),
("chen vs harada mitsuro (spanish mackerel)","06","13"),
("chen vs shimamura takashi (pen shell)","06","14"),
("morimoto vs tetsuo hagiwara (bamboo shoots)","06","15"),
("kobe vs yosei watanabe (mango)","06","16"),
("morimoto vs yasuhiko habuchi (asparagus)","06","17"),
("chen vs liang shuqing (pork belly)","06","18"),
("chen vs liang shuqing (konnyaku) overtime","06","19"),
("sakai vs kobayashi kumiko (mishima beef)","06","20"),
("morimoto vs kenichi miyanaga (sweetfish)","06","21"),
("chen vs kentaro (potato)","06","22"),
("kobe vs yasuhiro sasajima (eggplant)","06","23"),
("morimoto vs takaji yoshida (tofu)","06","24"),
("sakai vs shimokawa shuzo (jinhua pork)","06","25"),
("chen vs junichi itoh (yogurt)","06","26"),
("morimoto vs kajimoto takeshi (abalone)","06","27"),
("kobe vs sakai miyoko (blue crab)","06","28"),
("morimoto vs hirokazu handa (giant eel)","06","29"),
("sakai vs watabe masanobu (peach)","06","30"),
("chen vs miyazawa kaoru (carp)","06","31"),
("2000th dish: french vs chinese part i","06","32"),
("2000th dish: french vs chinese part ii","06","33"),
("sakai vs kyonori miura (squid)","06","34"),
("chen vs maruyama hideki (sardine)","06","35"),
("morimoto vs shuichi fuji (juvenile salmon)","06","36"),
("kobe vs shinya tasaki (tuna)","06","37"),
("sakai vs ron siegel (lobster)","06","38"),
("chen vs kagata kyoko (veal)","06","39"),
("morimoto vs tatsutoshi kumamoto (natto)","06","40"),
("kobe vs kensuke sakai (pumpkin)","06","41"),
("sakai vs kazumi nagayama (saury)","06","42"),
("chen vs hisao yaginuma (shanghai cabbage)","06","43"),
("kobe vs takatsugu sasaoka (maitake)","06","44"),
("morimoto vs marco molinari (porcini)","06","45"),
("sakai vs hazama mitsuo (duck)","06","46"),
("kobe vs yoneda hiromichi (octopus)","06","47"),
("chen vs mitsuo suganuma (shark fin)","06","48"),
("morimoto vs jiro ogue (turkey)","06","49"),
("chen vs xie huaxian (lobster)","07","01"),
("sakai vs kamimura kouei (cod)","07","02"),
("kobe vs costantino gemmoli (bell pepper)","07","03"),
("morimoto vs hiroyuki hakogi (yellowtail)","07","04"),
("morimoto vs tetsuji iio (king crab)","07","05"),
("kobe vs tsujiguchi hironobu (banana)","07","06"),
("sakai vs senba toshiya (asyra oyster)","07","07"),
("chen vs asao ryozo (sturgeon)","07","08"),
("morimoto retrospective part i","07","09"),
("morimoto retrospective part ii: morimoto vs nakamura komei (egg)","07","10"),
("sakai vs koji hosogai (ox tail)","07","11"),
("morimoto vs masahara seiya (angler)","07","12"),
("chen vs cui yufen (chinese cabbage)","07","13"),
("sakai vs tohru komori (udon)","07","14"),
("kobe vs franco canzoniere (tomato)","07","15"),
("morimoto vs yusuke yamashita (cod roe)","07","16"),
("morimoto vs yusuke yamashita overtime (scallions)","07","17"),
("chen vs okubo takeshi (bean sprout)","07","18"),
("sakai vs michel husser (lamb)","07","19"),
("chen vs spano stelvio (suckling pig)","07","20"),
("indonesian expedition part i","07","21"),
("indonesian expedition part ii","07","22"),
("kobe vs makoto osada (giant lobster)","07","23"),
("morimoto vs nakazawa keiji (sushi)","07","24"),
("sakai vs makio isao (black pork)","07","25"),
("morimoto vs michael noble (potato)","07","26"),
("chen vs tateno yuji (sea urchin roe)","07","27"),
("morimoto vs tanigawa yoshimi (pike eel)","07","28"),
("kobe vs shoji yamaoka (jumbo mushroom)","07","29"),
("chen vs dominique corby (foie gras)","07","30"),
("chen vs dominique corby overtime (asparagus)","07","31"),
("kobe vs sakai hiroki (eel)","07","32"),
("morimoto vs watanabe akira (cuttlefish)","07","33"),
("sakai vs yoshihide koga (stingray)","07","34"),
("morimoto vs shigematsu ryozo (sea bass)","07","35"),
("king of iron chef's tournament round one","07","36"),
("king of iron chef's tournament round two","07","37"),
("king of iron chef's tournament finals - part 1","07","38"),
("king of iron chef's tournament finals - part 2","07","39"),
("king of iron chef's tournament finals - part 3","07","40"),
("the millennium special","00","01"),
("new york special","00","02"),
("21st century special","00","03"),
("japan cup 2002","00","04"),
("new york special: rock crab","00","05"),
]
